<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: DejaVu Sans, sans-serif; color: #1a1a1a; font-size: 12px; }
  .header { border-bottom: 3px solid #d4af37; padding-bottom: 12px; margin-bottom: 20px; }
  .header h1 { margin: 0; font-size: 22px; }
  .header .tagline { color: #b87333; font-size: 11px; }
  .meta { width: 100%; margin-bottom: 16px; }
  .meta td { padding: 4px 8px 4px 0; vertical-align: top; }
  .label { color: #666; font-size: 10px; text-transform: uppercase; }
  table.lines { width: 100%; border-collapse: collapse; margin: 12px 0; }
  table.lines th { background: #12161d; color: #d4af37; text-align: left; padding: 8px; font-size: 11px; }
  table.lines td { border-bottom: 1px solid #ddd; padding: 8px; }
  .total { text-align: right; font-size: 16px; font-weight: bold; margin-top: 8px; }
  .footer { margin-top: 30px; border-top: 1px solid #ddd; padding-top: 10px; font-size: 10px; color: #666; }
</style>
</head>
<body>
<div class="header">
  <h1>Payment Receipt</h1>
  <div class="tagline">Ahmed — Own Every Square Foot. · Developed by Ahmed</div>
</div>

<table class="meta">
  <tr>
    <td><div class="label">Receipt No.</div><strong>{{ $receipt_number }}</strong></td>
    <td><div class="label">Payment Date</div>{{ $payment_date }}</td>
    <td><div class="label">Method</div>{{ ucfirst(str_replace('_', ' ', $method)) }}</td>
  </tr>
  <tr>
    <td><div class="label">Agency</div>{{ $agency['name'] }}</td>
    <td><div class="label">Tenant</div>{{ $tenant['name'] }}</td>
    <td><div class="label">Reference</div>{{ $reference ?? '—' }}</td>
  </tr>
  @if($lease)
  <tr>
    <td><div class="label">Lease</div>{{ $lease['lease_number'] }}</td>
    <td><div class="label">Property</div>{{ $lease['property'] ?? '—' }}</td>
    <td><div class="label">Unit</div>{{ $lease['unit'] ?? '—' }}</td>
  </tr>
  @endif
</table>

<table class="lines">
  <tr><th>Allocation</th><th style="text-align:right">Amount ({{ $currency }})</th></tr>
  @forelse($allocations as $a)
  <tr><td>{{ $a['target'] }} <span style="color:#666">({{ str_replace('_', ' ', $a['bucket']) }})</span></td>
      <td style="text-align:right">₨{{ number_format($a['amount'], 2) }}</td></tr>
  @empty
  <tr><td colspan="2" style="color:#666">Unallocated — held as tenant credit.</td></tr>
  @endforelse
</table>

<div class="total">Received: ₨{{ number_format($amount, 2) }}</div>
<p>Unallocated credit: ₨{{ number_format($unallocated, 2) }}<br>
Tenant outstanding balance: ₨{{ number_format($tenant_balance, 2) }}</p>

@if($notes)<p><strong>Notes:</strong> {{ $notes }}</p>@endif

<div class="footer">
  Generated by APRMS · {{ now()->toDateTimeString() }} · Posted by {{ $posted_by ?? '—' }}<br>
  This receipt records a manually recorded payment. No external payment confirmation is implied.
</div>
</body>
</html>
